GET http://localhost:3001/api/daos/0x3BA8aE675ab5c19579dc7144635e39c5418252EB



###
POST http://localhost:3001/api/daos
Content-Type: application/json

{
  "name": "NeuroSyncDAO",
  "imageUrl": "https://ik.imagekit.io/ovba0cdvm/image%20(23).jpg",
  "tokenAddress": "0x8936CA9f35Df2c5ad69127c9323865D4483Fd6d2",
  "tokenSymbol": "NVT",
  "governanceContractAddress": "0xE47488Dc1976070957fC53919D23866F123997A1",
  "description": "NeuroSyncDAO is a decentralized autonomous organization powered by the NeuroVote Token on the Sonic Blockchain. It enables community-driven governance, allowing members to vote on proposals, fund initiatives, and shape the future of the ecosystem. With a focus on"
}


###
GET https://api.dotfeeds.com/api/daos/all



###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "walletAddress": "0x18241781b17b878cFC16B109035904C8E5073e73"
}

###
GET http://localhost:3001/api/users/wallet/0x1459ca34BC6BAeD78557801605Fe8487777b30e1


// Create a new agent

###
POST http://localhost:3001/api/agents
Content-Type: application/json

{
  "userId": "0x18241781b17b878cFC16B109035904C8E5073e73",
  "daoId": "lLptmzuxzVPPu525Kix5",
  "isAutoVoteEnabled": true,
  "governanceStrategy": "Decentralization-Focused",
  "riskProfile": 90,
  "voteAlignment": "Align with top governance influencers"
}


###
GET http://localhost:3001/api/agents/user/0x18241781b17b878cFC16B109035904C8E5073e73


###
POST http://localhost:3001/api/agents/toggle-delegation
Content-Type: application/json

{
  "userId": "0x18241781b17b878cFC16B109035904C8E5073e73",
  "agentId": "8UuAboIgTMZ0cOHz8AXm"
}


###
POST http://localhost:3001/api/proposals/create
Content-Type: application/json

{
  "title": "Implement AI-Powered Trading Strategies",
  "description": "Deploy AI-driven trading bots to optimize asset allocation and maximize returns from market opportunities, ensuring efficient and automated fund management.",
  "daoId": "qC4GZsNGSRTLMKQnm85M"
}




###
GET http://localhost:3001/api/proposals/user/0x1459ca34BC6BAeD78557801605Fe8487777b30e1


###
GET http://localhost:3001/api/votes/agent/qC4GZsNGSRTLMKQnm85M-0x1459ca34BC6BAeD78557801605Fe8487777b30e1




